# -*- coding: utf-8 -*-
"""algorithm-assetipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jhEFmNzZzRH3d5Vc3ZIkiwjEXuh47yZc
"""

# pip install mne

import mne 
import numpy as np 
import pandas as pd

raw_edf = mne.io.read_raw_edf("/content/drive/MyDrive/datasets/sub-01_ses-01_eeg_sub-01_ses-01_task-hfo_eeg.edf")

raw_edf.plot_psd()

np.mean(raw_edf)